name: "${name}"
main: ru.sliva.bypass.ServerProBypass
version: "${version}"
api-version: 1.19
description: "${description}"
author: sliva
load: STARTUP
commands:
  say:
    description: "Replaces vanilla /say command"
    usage: '/say <msg>'
