name: "${name}"
main: ru.sliva.bypass.ServerProBypass
version: "${version}"
api-version: 1.19
description: "${description}"
author: sliva
load: STARTUP
libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.0"
commands:
  say:
    description: "Replaces vanilla /say command"
    usage: '/say <msg>'
